### ISSUE TITLE
3.33 and 3.34 google says it's dangerous.

### ISSUE THREAD

**Issue by raxele123** [djravine/idlecombos#22]
3.33 and 3.34 google says it's dangerous. Please fix? Also you saw my new hotkey suggestion right? :3

**Comment by djravine** [comment]
Can you give me more info on what google is saying?

 **Online Virus Scan:** https://www.virustotal.com/gui/url/cd5fa1d5d6fc1594ae48a1096c39d335999e6fe316d111e4bc14b0bd3460e3fe?nocache=1

**Comment by djravine** [comment]
**HotKeys:** https://github.com/djravine/idlecombos/discussions/17

**Comment by djravine** [comment]
I'll remove the style system to fix this.

**Comment by djravine** [comment]
Fixed in latest release https://github.com/djravine/idlecombos/releases/tag/v3.35

**Comment by djravine** [comment]
https://github.com/djravine/idlecombos/releases/tag/v3.71

Style system has been added back in and 2 builds are available:
- Build with Themes
- Build without Themes
