### ISSUE TITLE
[BUG] Open Event Chests isn't working.

### ISSUE THREAD

**Issue by raxele123** [djravine/idlecombos#28]
Open Event Chests isn't working. Owned and max aren't showing up and I have no clue why.

![image](https://user-images.githubusercontent.com/12002095/212287860-848c61f4-eba4-4c2e-b0f6-12583cd05468.png)

**Comment by djravine** [comment]
I wish I had as much champion power as you.. lol

**Comment by djravine** [comment]
PR https://github.com/djravine/idlecombos/pull/29

**Comment by djravine** [comment]
Released [v3.38](https://github.com/djravine/idlecombos/releases/tag/v3.38)
