### ISSUE TITLE
[BUG] Codes starting with # still can't be pasted

### ISSUE THREAD

**Issue by THDigi** [djravine/idlecombos#31]
**To Reproduce**
Steps to reproduce the behaviour:
1. tools -> redeem codes
2. paste:
```
ETEN-VIBS-PELF
#SEA-SONG-RIND
AKAS-WAWL-KZAZ
```
3. only 2 codes get pasted, the middle one is ignored.

**Expected behaviour**
I expect all valid codes to be pasted.

Used current latest version, 3.40 on windows 10, AHK version seen in screenshot too.

![screenshot](https://i.imgur.com/nQFcq6C.png)

**Comment by djravine** [comment]
Able to reproduce, will investigate.

**Comment by djravine** [comment]
From investigation, any code that starts with these chars `@ # $ % ^ & ! *` will fail REGEX validation.

**Comment by djravine** [comment]
```
regexpPatternOld := "P)\b(?<![A-Za-z0-9-/@#$`%^&!*])([A-Za-z0-9-@#$`%^&!*]{12,20})(?![A-Za-z0-9-/@#$`%^&!*])"
regexpPatternNew := "P)(?<![A-Za-z0-9-\/@#$`%^&!*_=+\(\)\{\}\[\]])([A-Za-z0-9-@#$%^&!*]{12,20})(?![A-Za-z0-9-\/@#$`%^&!*_=+\(\)\{\}\[\]])"
```

Testing: https://regex101.com/r/BvGo0z/2

**Comment by djravine** [comment]
Released https://github.com/djravine/idlecombos/releases/tag/v3.41
