### ISSUE TITLE
[BUG] Redeem code & results windows are getting lost under other windows

### ISSUE THREAD

**Issue by THDigi** [djravine/idlecombos#33]
Can't alt+tab to redeem code or code results windows and they don't show up in the taskbar either.

This makes them a real PITA to get back to, having to move other windows aside to be able to get to them.

Please give them taskbar buttons again (which hopefully makes them alt+tabable too), in v3.0 they had taskbar buttons.

Other windows still have taskbar buttons, like briv stack calculator.

**Comment by djravine** [comment]
Released [v3.42](https://github.com/djravine/idlecombos/releases/tag/v3.42)
