### ISSUE TITLE
[FEATURE] Skip loading data and chest buy and open number.

### ISSUE THREAD

**Issue by raxele123** [djravine/idlecombos#35]
A on/off setting to skip the "Loading Data... Please wait..." for blacksmith scrolls or just in general. The time it takes and the lag it causes is annoying. Course once you do that your scroll/everything count won't change so unless you know the exact number of scrolls you have the only time you know when you run out is when you get an error telling you have no more scrolls. But I'm fine with that. What I'm annoyed by is the time it takes and the fact that idle combos is completely frozen while loading data after using blacksmith scrolls.

You know how blacksmith scrolls by default shows you the maximum number of scrolls you can use when you first open it right? Could you please apply this to the amount of chests you can buy/open too? Odd that this isn't here by default.

**Comment by raxele123** [comment]
Busy with work? Since you usually just plow through features and bugs. Well I'll just keep waiting. The hotkeys are working great 😸

**Comment by djravine** [comment]
I can understand the loading is annoying, but its a necessary evil here.
Without the loading of the data the app would be pretty useless.

**Comment by djravine** [comment]
I'm not sure what you mean with the chest prompt, they show you how many you can open and buy.
![2023-02-01 08 43 29](https://user-images.githubusercontent.com/155802/215900798-12a78885-b425-4f7c-8a37-bfc60d10013d.png)
![2023-02-01 08 43 52](https://user-images.githubusercontent.com/155802/215900814-a804cb65-0bb7-40bb-b710-7bca980e1412.png)
If you are talking about EVENT CHESTS, the MAX will only show during events, when you can actually buy them.

**Comment by raxele123** [comment]
So no way to counter the "Loading Data... Please wait..." and allow you to click or do other things while it is happening?

Ah you didn't get what I mean. I mean like in the bar where you type in the number the number is already pre typed. It is with the blacksmith scrolls but isn't with the chests.

**Comment by djravine** [comment]
Ahhhh, I get you now. I'll add that in.

I'll keep looking at the GUI freezing during loading tho.

**Comment by djravine** [comment]
I have changed the way the server call is handled, it might be faster than previous.... Let me know.

**Comment by raxele123** [comment]
Doesn't feel any faster. Oh well. Perhaps leave it alone for now until you get any bright ideas you would like to try. So uh dark mode. Any ideas on that part? A dark mode that doesn't trigger the windows virus detection?
