### ISSUE TITLE
[FEATURE] Bounty Contracts

### ISSUE THREAD

**Issue by raxele123** [djravine/idlecombos#39]
Is it possible to use them though IdleCombos? Its slow and tedious trying to get rid of Small and Medium Bounty Contracts in game during events so is it possible to do it in IdleCombos with the game closed or something? Add a Bounty tab to IdleCombos and all the hotkeys with it? Or do you not get event tokens when doing it this way that's why it isn't on IdleCombos?

**Comment by djravine** [comment]
I'll look into it, It should be possible

**Comment by djravine** [comment]
So after updating the code for Bounty Contracts.
I found out that the Bounty Contracts are calculated CLIENT side, not SERVER side.
Unfortunately, there is no real way to automate this process using the Idle Combos AutoHotKey script.

**Comment by djravine** [comment]
I will leave the code in DEVELOP for now and do some more testing to see if there is anything I can do

**Comment by djravine** [comment]
Release [v3.46](https://github.com/djravine/idlecombos/releases/tag/v3.46)

**Comment by djravine** [comment]
I'll leave this issue open for your feedback on how it works.

**Comment by djravine** [comment]
I need to update the ZIP builder... it didn't include the images in the automatic release build.
I'll fix it for next build.

**Comment by djravine** [comment]
Fixed images folder in Release [v3.47](https://github.com/djravine/idlecombos/releases/tag/v3.47)

**Comment by raxele123** [comment]
Well there's another event going on. If theres any time to try if bounty contracts can make event tokens spawn though idlecombos its now.
