### ISSUE TITLE
[BUG] Buy/Open Event Chest Broken.

### ISSUE THREAD

**Issue by raxele123** [djravine/idlecombos#40]
It says owned 0 even if you have chests. I think that update with client and server stuff broke it.

Edit: I think everything is broken due to that update with client and server stuff. By everything I mean the blacksmith too.

**Comment by djravine** [comment]
Everything is still working on my end, I can revert the server API call change I made.

**Comment by djravine** [comment]
It appears the the API Server default `ps7` is no longer responding.
It might be under maintenance or decommissioned.

I have changed the default to `master` which seems to fix the data loading issue.

**Comment by djravine** [comment]
You may have to manually change this setting yourself, as it is saved in the user settings for this app.

**Comment by djravine** [comment]
Discussion: https://github.com/djravine/idlecombos/discussions/42
