### ISSUE TITLE
[BUG] Redeem Codes doesn't work on Windows 11

### ISSUE THREAD

**Issue by heldenwelt** [djravine/idlecombos#43]
Thanks for the Code... on Windows 10 it works just fine.
But on Windows 11 "Redeem Codes" throws a "Unknown or no Results"

**Comment by bpxbpx** [comment]
It's working here on Windows 11. Double-check your configuration again, it should work.

**Comment by djravine** [comment]
If you are also having issues loading data (everything is empty) you may need this https://github.com/djravine/idlecombos/discussions/42

**Comment by djravine** [comment]
If there are any more updates to this issue please let me know, otherwise I'll close this issue in the next few days.
