### ISSUE TITLE
[BUG] Buy/Open ANY Chests - Server Errors and 24 Hour Soft Bans

### ISSUE THREAD

**Issue by raxele123** [djravine/idlecombos#45]
Buy Event Chests still totally broken :( Give it a check and you'll see what I mean. Or not since this event is ending soon.

**Comment by djravine** [comment]
Can I have a bit more of a description, 'really broken' doesn't help much I'm afraid

**Comment by raxele123** [comment]
My bad. Should've screenshotted the error. I took this screenshot after the event ended but I'm pretty sure its the same thing I got during the event.

![image](https://user-images.githubusercontent.com/12002095/218599113-c44e7af3-60e5-4348-be4d-c390afd79329.png)

**Comment by djravine** [comment]
This appears to be new, and multiple reports on Discussion https://github.com/djravine/idlecombos/discussions/42

**Comment by djravine** [comment]
Release [v3.48](https://github.com/djravine/idlecombos/releases/tag/v3.48) now sets the default server name to `ps20`
You will need to manually change if you have already save settings previously.

**Comment by raxele123** [comment]
First theres this. I have plenty of fish yet it says the max I can buy is 0

![image](https://user-images.githubusercontent.com/12002095/220749855-e7a78b4a-8c8d-4fab-96b4-a0bc6d250284.png)

Second there is this when you try to continue anyways. 

![image](https://user-images.githubusercontent.com/12002095/220749998-37ca14c5-0fc3-4f3e-9507-dda3794a11ed.png)

I'm counting on you! Please fix this before the event ends hahaha... Thank you for all the effort you put into this for us.

**Comment by djravine** [comment]
Sorry for the delay, been super busy with work.
I'll try to look at this on the weekend as a priority

**Comment by djravine** [comment]
I'll close this for now. Please create a new issue during the next event if this is still an issue.
