### ISSUE TITLE
[BUG] Startup bug because of settings.json

### ISSUE THREAD

**Issue by cerveau23** [djravine/idlecombos#49]
I don't know why, but it seems that by default as well as upon saving new settings the saved value for "firstrun" is 1, which causes later launches of the program to be unable of getting userid and hash, therefore disabling all functions, as well being unable to load anything in the "setting" tab.

Deleting the whole folder and recopying it from the zip fixes it for one launch.
Going into "idlecombosettings.json" and changing the value for "firstrun" from 1 to 0 fixes it completely for what I've seen, as long as you don't save new settings.

Plz note that I have not tested downloading a fresh zip, maybe my file has a corrupted bit.
[idlecombos-master.zip](https://github.com/djravine/idlecombos/files/10847768/idlecombos-master.zip)

**Comment by djravine** [comment]
I have run a few tests and cannot seem to reproduce this bug.
