### ISSUE TITLE
[BUG] Discord invite link expired?

### ISSUE THREAD

**Issue by TorchCmdr** [djravine/idlecombos#50]
**Describe the bug**
https://discord.com/invite/N3U8xtB page says only "Invite Invalid: This link may be expired, or you might not have permission to join."

**To Reproduce**
1. Go to 'Help'
2. Click on 'Discord Support Server'
3. See ![image](https://user-images.githubusercontent.com/41968199/222974477-cd92e58a-7927-4940-88a1-b71753f51433.png)

**Expected behaviour**
An actual Discord server where a new user can post!

**Desktop:**
 - OS: Windows 10 Pro 22H2
 - Browser: tried Edge and Chrome.

**Comment by raxele123** [comment]
What discord server is that link supposed to go to?

**Comment by djravine** [comment]
This went to the old discord server from before my time.
I may setup a new discord in the new future.

**Comment by TorchCmdr** [comment]
You should remove the broken link until you make up your mind!

**Comment by djravine** [comment]
I have created a Discord server and added in an invite link with no expiry date.
