### ISSUE TITLE
[BUG] Can't get user data

### ISSUE THREAD

**Issue by kisame1313** [djravine/idlecombos#55]
It can't find `webRequestLog.txt` file for Steam version
Select path to file manually and it's gave me such error
![image](https://user-images.githubusercontent.com/60168090/224514548-871e0302-3829-46d6-9347-2c32f3414ce3.png)

**Comment by djravine** [comment]
I'll have a look at it.

**Comment by djravine** [comment]
Hmm, everything is working for all 3 versions for me (Epic/Steam/Standalone).
I am able to get data and its able to parse the web request log.
If possible can you send me your web request log?
I am on Discord if you want to PM me the file (instead of having it public on here)

**Comment by djravine** [comment]
Also, if you enable the log, it will dump to data from the request to the API.
That will also help if there is a problem getting data from the API.

**Comment by kisame1313** [comment]
Here is both files
I've deleted webRequestLog.txt and started game. Didn't help
I'm running it on Win 10 
Steam version, but script can't find it 
[webRequestLog.txt](https://github.com/djravine/idlecombos/files/10950602/webRequestLog.txt)
[idlecombolog.txt](https://github.com/djravine/idlecombos/files/10950603/idlecombolog.txt)

**Comment by djravine** [comment]
Do you have steam installed in the default steam location?
`C:\Program Files (x86)\Steam\steamapps\common\IdleChampions\`
This is the folder where it looks for the game by default.

Or is it installed elsewhere? (and you have to manually select the `webRequestLog.txt`)

**Comment by kisame1313** [comment]
I've looked into [webRequestLog.txt](https://github.com/djravine/idlecombos/files/10950602/webRequestLog.txt)
And all is here 
`getuserdetails&language_id=3&user_id=300**31&hash=9c***4f3adce354fce5f01d1***3be70&instance_key=665***069`
And yes, I've installed Steam in non-default directory 
Yes, I've selected path to **webRequestLog.txt** manually

**Comment by StoobertB** [comment]
I think the problem is on this line: `FoundPos := InStr(oData, "getuserdetails&language_id=1&user_id=")` because it's looking for a line in the log that has `language_id=1` (to match the webrequest line). Your request has `language_id=3`. Try manually editing the webRequestLog.txt file to change that ID to 1 and see if it works.

**Comment by kisame1313** [comment]
Yeah, It helps 
Manually changing file is not worked 
But when I've changed language in game settings it's worked
Thank you!
