### ISSUE TITLE
[BUG] 3.52 not loading any data

### ISSUE THREAD

**Issue by Brady84** [djravine/idlecombos#58]
**Describe the bug**
Seems to be locked to s25 & doesn't load any information from the game, replacing it with 3.51 allows it to work again

**To Reproduce**
Steps to reproduce the behaviour:
1. Use Github Desktop
2. Update
3. Open .ahk

**Expected behaviour**
3.52 does nothing, does not load data, not sure if it is attempting to use a server that is offline or another reason

**Screenshots**
https://i.gyazo.com/7d7cdcc01370936c2b51474e60e899b0.png <-- 3.51 events tab
https://i.gyazo.com/1589d0381652bf82cee0b4c72b86fb30.png <-- 3.52 not loading anything 

**Desktop (please complete the following information):**
 - OS: W11
 - Version 3.52 & 3.51

**Additional context**

**Comment by djravine** [comment]
I'll have a look at this ASAP, cheers.
I did just recently implement more detection for play servers and if the API is returning errors.

**Comment by djravine** [comment]
From the look of it, it should be `ps25` not `s25`.
I added in code to detect the play server every time Idle Combos is launched to make sure you are always using the correct play server.
The `webrequest.log` is rewritten every time you load up Idle Champions game.

**Comment by Brady84** [comment]
Sorry for the late reply, Updated to 3.54 & did the above, it does find the correct server, but tries to load s19 and not ps19. If I manually change it to ps19, save then update it loads all data and works, once I exit/reload it reverts back to s19. 

Also tried editing idlecombosettings.json from s19 to ps19, but Its being auto-updated by your code above (back to s19)  checked webrequest.log it is showing as ps there  "success":true,"play_server":"http:\/\/ps19.idlechampions.com\/~idledragons\/"

**Comment by djravine** [comment]
Cheers,

I'll work on the server detection and give the option to disable it in the next release.

**Comment by djravine** [comment]
Should be fixed in the new version, let me know if it is still a problem
