### ISSUE TITLE
[BUG] Sometimes not all codes are redeemed

### ISSUE THREAD

**Issue by THDigi** [djravine/idlecombos#65]
**Describe the bug**
For example giving it 3 codes to redeem it only shows 2 chests received, absolutely nothing about the 3rd.
Immediately resubmitting the same codes does redeem the missing one.

**To Reproduce**
No idea what causes it, seems kinda random... or maybe I only noticed the few times I had it but happens way more often...
I did however have the game closed when I did this and it idle combos froze for a while before asking me for "update server?" thing.

**Screenshots**
Submitted 3 codes:
![](https://i.imgur.com/HrKEWhV.png)
It showed results only for 2:
![](https://i.imgur.com/dq3QzRR.png)
Re-submitting:
![](https://i.imgur.com/pq7zJg7.png)

**Expected behaviour**
I expect all codes to be used =)

Can you at least check the code amount vs results amount (including invalid ones and such) and alert user to resubmit because not all of them got results?

**Comment by djravine** [comment]
I'll have a look at this

**Comment by dhusemann** [comment]
I had thought of writing a 2 run system because that issue, which started around the time of IC client being its own denial of service. but it certainly is a over the wire issue as it is random of which code is dropped and can be a miss in the middle of the stream.

**Comment by djravine** [comment]
We have a request to parse the chest redeem log when processing chest codes.
That might be a way to pick up the failed code and re-run it with a 2nd time if it fails the first time.
