### ISSUE TITLE
[BUG] Won't remember location of webrequestlog

### ISSUE THREAD

**Issue by bpxbpx** [djravine/idlecombos#67]
**Describe the bug**
At every start of idlecombos it will tell me that it can't find the location of webrequestlog.txt and whether I want to choose the install directory manually. I assume that's related to my Steam files not being on my C:\ drive. But when I then click on yes to choose for it manually it will open the correct directory. So it does somewhat save the correct location but can't apply it at launch?

**Expected behaviour**
It saves the location of webrequestlog.txt in a way so it can automatically grab the info at launch

**Desktop (please complete the following information):**
 - Win 11
 - idlecombos 3.57
 - running ahk file (not compiling to exe)

**Comment by djravine** [comment]
This is a bug, as it only looks for the default install location and doesn't save the actual location to the settings.
`global GameInstallDirSteam := "C:\Program Files (x86)\Steam\steamapps\common\IdleChampions\"`
