### ISSUE TITLE
[BUG] idlecombos stopped redeeming chests

### ISSUE THREAD

**Issue by SjurWarEagle** [djravine/idlecombos#69]
**Describe the bug**
idlecombos stopped redeeming chests

**To Reproduce**
Steps to reproduce the behaviour:
1. open redeem code, use any code

**Expected behaviour**
chest is redeemed

**Screenshots**
<img width="178" alt="image" src="https://github.com/djravine/idlecombos/assets/7311103/5b0cdb9b-176d-4264-8d84-50aa56c3f88c">
<img width="182" alt="image" src="https://github.com/djravine/idlecombos/assets/7311103/a7d2acbf-ee03-4e5f-9e04-4229ef5fdd99">
at end, the issue is visible:
<img width="224" alt="image" src="https://github.com/djravine/idlecombos/assets/7311103/578f8892-b9ff-4f3f-825f-a70a482cf3fc">

**Desktop (please complete the following information):**
 - OS: Win11
 - Browser chrome
 - Version 3.58

**Additional context**
redeemcodelog.json:
```
{"success":true,"switch_play_server":"http:\/\/ps21.idlechampions.com\/~idledragons\/","memory_usage":"6 mb","apc_stats":{"gets":0,"gets_time":"0.00000","sets":0,"sets_time":"0.00000"},"db_stats":{"23":false,"1":false,"24":false},"processing_time":"0.00308"}
```
SINKSHMOMOAS

it gives a message like this for every code.
for me it looks like the login failed:
<img width="190" alt="image" src="https://github.com/djravine/idlecombos/assets/7311103/6a49019d-f526-4e0f-a422-bb28b1f97ee9">

**Comment by Shebuka** [comment]
I have the same problem

**Comment by Chaosbender** [comment]
yes, the program does not load any game-data anymore.

**Comment by djravine** [comment]
I have made a patch for this issue.
Will release shortly.

**Comment by Shebuka** [comment]
Login now works but I still can't redeem chests, same `Unknown or No Results` error

**Comment by mileippert** [comment]
Setting the server name to the one visible in redeemcodelog.json ("switch_play_server") seems to bring it back to working condition. Maybe the redeem logic does not correctly handle that field?

**Comment by Shebuka** [comment]
Can confirm what @mileippert reported, steps to make it work until patched: 

1. try send the default code and get the error, 
2. in redeemcodelog.json look at "switch_play_server" and copy the server name (`psXX`), 
3. go to **Settings**, 
4. write in **Server** the server name, 
5. uncheck the "Get server at start", 
6. hit **Save**, 
7. hit **Reload**, 
8. hit **Update**.

Now you can redeem the chests.

**Comment by djravine** [comment]
I have been trying to reproduce this bug on the latest version and am unable to get the same error.
Seeing as the `switch_play_server` is being picked up and changed on the fly in the server call its automatically changing the server and allow me to redeem code correctly.

**Comment by djravine** [comment]
I have a few other changes to test first, so I will release this new version asap.

**Comment by SjurWarEagle** [comment]
<img width="487" alt="image" src="https://github.com/djravine/idlecombos/assets/7311103/8644a080-b938-46f1-b0d5-a98a9b1834f9">
still broken for me, git hash 4013ba4f10ba3130f2058aa687d6279cffa04a6b (master at point of posting)

it does not take over the server that it gets and shows in the log, if entering manually it's fine
{"success":true,"switch_play_server":"http:\/\/ps19.idlechampions.com\/~idledragons\/","memory_usage":"2 mb","apc_stats":{"gets":0,"gets_time":"0.00000","sets":0,"sets_time":"0.00000"},"db_stats":{"23":false,"1":false,"22":false},"processing_time":"0.00398"}

**Comment by djravine** [comment]
Illl do some more testing with this and see if I can reproduce it.

**Comment by Shebuka** [comment]
Still happening.
Interesting is that the json file is corrupted:
![Screenshot 2023-10-03 182143](https://github.com/djravine/idlecombos/assets/10927011/c1a782e9-3964-4be2-a599-1412fd21c5ae)
