### ISSUE TITLE
[BUG] Still can't redeem codes

### ISSUE THREAD

**Issue by Ikkegwn** [djravine/idlecombos#76]
Still can't redeem codes like in the previous post

**Comment by djravine** [comment]
https://github.com/djravine/idlecombos/issues/69

**Comment by djravine** [comment]
Everything is working on my end.
Is the option `Get Play Server Name automatically?` enabled?

**Comment by Ikkegwn** [comment]
![IREoMZ7](https://github.com/djravine/idlecombos/assets/20224645/9fbe808a-55e4-455f-95e7-b07e18115f5c)
This is what i have, codes just don't redeem
Steam version.
I just made it look like you have it setup but i have no clue what's going on

**Comment by Ikkegwn** [comment]
Somehow, it's working now, i have no clue how, i'll be closing this
