### ISSUE TITLE
Both STEAM and EPIC versions loaded won't setup Steam

### ISSUE THREAD

**Issue by dhusemann** [djravine/idlecombos#8]
skips option to setup Steam account

**Comment by djravine** [comment]
Can I have a little more info?

You can manually select the setup via the FILE menu.
![2022-12-05 09 10 13](https://user-images.githubusercontent.com/155802/205521311-bbfb48b3-327a-4f7e-ad46-d8338502fed8.png)

**Comment by djravine** [comment]
Any more info?

**Comment by dhusemann** [comment]
Sorry spent the last month in the hospital, 
Yes, to get some of the features to work Had to load the  Epic client even though I had used Steam as a client.  Initially, Idlecombos was split between the clients as separate builds 

But think it is a Windows issue, if set to run from task bar,  it always says that it has to reset the settings then it loads the Epic client. then it just started loading Auto hotkey client, after it started doing that could right click and pull up the correct version and run

**Comment by djravine** [comment]
I have updated the code to now store the last detected game client.
If you last detected STEAM, It should now auto load STEAM on opening.
A new release should be out today.

**Comment by djravine** [comment]
Now in Releases, open a new ticket if its still not working as expected
