### ISSUE TITLE
Valid chest code ignored from paste feature

### ISSUE THREAD

**Issue by THDigi** [djravine/idlecombos#9]
A recent valid code `#ONBREAKSOON` seems to be completely skipped when using paste button from the redeem code dialogue.

**Comment by djravine** [comment]
I just tested this code and it appears to be working by converting the `#` to its URL Encoded version.

`Expired:
%23ONBREAKSOON`

**Comment by djravine** [comment]
Feel free to open a new issue if this happens again and I'll investigate further

**Comment by djravine** [comment]
New Issue https://github.com/djravine/idlecombos/issues/31
