### ISSUE TITLE
[BUG] Codes Not Found anymore

### ISSUE THREAD

**Issue by LockMan007** [djravine/idlecombos#92]
Codes no longer found

![image](https://github.com/djravine/idlecombos/assets/13595927/4513a7f7-308a-4591-a872-0cde675627c9)

**Comment by djravine** [comment]
I have just tested this on my pc and its all working as expected.

**Comment by LockMan007** [comment]
UPDATE: It seems that VPN's are now blocked for getting the update list.
I have to whitelist AHK to get the updates.

**Comment by djravine** [comment]
Thanks for the investigation and reply.
I'll add this into the README for future reference.
